format = "$character"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[➜](bold red)"

add_newline = false

[palettes.nord]
dark_blue = '#5E81AC'
blue = '#81A1C1'
teal = '#88C0D0'
red = '#BF616A'
orange = '#D08770'
green = '#A3BE8C'
yellow = '#EBCB8B'
purple = '#B48EAD'
gray = '#434C5E'
black = '#2E3440'
white='#D8DEE9'

palette = "nord"
